### ISSUE TITLE
Tooltips are broken in the 'opinions' section

### ISSUE THREAD

**Issue by ColinEberhardt** [StateOfJS/State-of-JS-2019#11]
<img width="1072" alt="Screenshot 2019-12-19 at 06 26 46" src="https://user-images.githubusercontent.com/1098110/71150161-97db7680-2228-11ea-93bd-38105bf335c8.png">

https://2019.stateofjs.com/opinions/

Looks like some sort of failed look-up (awesome survey BTW - fascinating results)

**Comment by SachaG** [comment]
Thanks, I'll fix it.
