### ISSUE TITLE
Type on "Javascript Flavors"

### ISSUE THREAD

**Issue by waplet** [StateOfJS/State-of-JS-2019#13]
![image](https://user-images.githubusercontent.com/5472594/71154945-602ef780-2245-11ea-8c87-5a143d3f0b3d.png)
"ojurescript"

**Comment by waplet** [comment]
Update:
Ok, it's not a type, as the "clojurescript" is there, it's only cut.

**Comment by SachaG** [comment]
I'll fix it, thanks.
