### ISSUE TITLE
[en-US] page.notfound on Support Us page

### ISSUE THREAD

**Issue by ottosson** [StateOfJS/State-of-JS-2019#15]
I get what looks like a translation error on the last/support page of the survey in the top-right corner, and the link goes to a 404:

![image](https://user-images.githubusercontent.com/3355320/71156229-d892ba00-223f-11ea-8436-06c6e31fcf4e.png)

**Comment by plouc** [comment]
Fixed by https://github.com/StateOfJS/State-of-JS-2019/commit/e5f1d9e261dac868396dc26647e2ed945baae8b6
