### ISSUE TITLE
"CSS's rate of change" instead on "JS's rate of change" 

### ISSUE THREAD

**Issue by BernierMaxence** [StateOfJS/State-of-JS-2019#16]
Seems like an unfortunate copy / paste ;) The first paragraph of the "Opinions" sections mentions CSS and not JS. 
![Capture d’écran 2019-12-19 à 09 30 57](https://user-images.githubusercontent.com/20169057/71157630-a9ca1300-2242-11ea-9cd5-18c2ad496249.png)

**Comment by Razzeee** [comment]
It might not be the only page, as I skimmed over some page before that, where it felt like the text was wrong.

**Comment by SachaG** [comment]
Sorry! As you probably guessed we used the State of CSS repo as a starting point and some things just didn't get changed.
