### ISSUE TITLE
"Syntax" chart has incorrect label: [en-us] features.usage.used_it: 4.1%

### ISSUE THREAD

**Issue by Ben-Kincaid** [StateOfJS/State-of-JS-2019#18]
https://2019.stateofjs.com/features/syntax/

Hover over any of the percentages in the horizontal meter charts - looks like a string literal of the variable is being output rather than the constant itself.

![image](https://user-images.githubusercontent.com/30325728/71161146-aceee000-21fd-11ea-9a5c-afb101f27ca6.png)

**Comment by SachaG** [comment]
Thanks, I'll fix it.
