### ISSUE TITLE
Colors of map and other charts / diagrams

### ISSUE THREAD

**Issue by dospolov** [StateOfJS/State-of-JS-2019#20]
Mostly all charts follow an obvious pattern: more saturated color means the biggest percentage.
![image](https://user-images.githubusercontent.com/670682/71164512-ec4a1a80-2257-11ea-961a-c9194deefeec.png)
But this not like that on maps:
![image](https://user-images.githubusercontent.com/670682/71164532-f704af80-2257-11ea-8967-95b76e9a4ebe.png)
It's not transparent from the first glance, because you have 3 different colors and you should map it somehow to percentage value in your head; or look on a legend all the time.

I suggest using the same schema: grey to red with different saturation levels.

**Comment by SachaG** [comment]
I agree, but if you look at this year's chart it's less confusing. https://2019.stateofjs.com/demographics/#country
