### ISSUE TITLE
Demographics Count

### ISSUE THREAD

**Issue by Aprillion** [StateOfJS/State-of-JS-2019#21]
In https://2019.stateofjs.com/demographics/, when I switch from Percents to Count tab, the color of countries changes to almost-all red, but the legend stays in %:
![demographics count legend bug](https://user-images.githubusercontent.com/1087670/71166676-83f93a00-2253-11ea-98ef-61a9b89d8f2d.png)

Observed in Win 10 Firefox and Chrome.

Expected: the legend should change to absolute numbers.

**Comment by SachaG** [comment]
Yes, the legend doesn't adapt to both scales. Good point.

**Comment by plouc** [comment]
Fixed by https://github.com/StateOfJS/State-of-JS-2019/pull/41
