### ISSUE TITLE
Svelte experience over 20 years

### ISSUE THREAD

**Issue by didiercatz** [StateOfJS/State-of-JS-2019#22]
As far as I’m aware, the Svelte framework has only existed for a couple of years. The first commit on the GitHub repository was in _November 2016_. How is it possible that people are able to pick 5, 10 or 20+ years of experience? It would make the overall statistics skewed wouldn’t it?

**Comment by Nicholaiii** [comment]
It's not experience with the framework, it's the amount of users of the framework that has this many years of experience with JavaScript. (So as to form an idea of what people with different levels of experience prefer)

**Comment by didiercatz** [comment]
Aah, thanks for clarifying. That makes much more sense!

**Comment by SachaG** [comment]
Yes, I added a note to clarify this. Sorry for the confusion!
