### ISSUE TITLE
Should write ins for "reactnative" be grouped into React Native?

### ISSUE THREAD

**Issue by rickhanlonii** [StateOfJS/State-of-JS-2019#24]
I noticed in the other tools section that there are 12 write ins for "reactnative", should those be grouped into React Native? https://2019.stateofjs.com/mobile-desktop/other-tools/

**Comment by SachaG** [comment]
Ideally yes but we don't have an automated process to do that currently. Since it's an edge case we'll leave it to be addressed next time.

**Comment by rickhanlonii** [comment]
That makes sense - for this case it may make sense to handle manually as a one-off since it's shown in the "Other Tools section" and displayed as "React Native" which is confusing:

<img width="1407" alt="Screen Shot 2019-12-26 at 11 20 51 AM" src="https://user-images.githubusercontent.com/2440089/71482671-dc8b8280-27d1-11ea-9154-3343b0915ea4.png">
