### ISSUE TITLE
Some Year Labels Reversed on Left Side of Overview Chart?

### ISSUE THREAD

**Issue by VikR0001** [StateOfJS/State-of-JS-2019#30]
Is it possible that some year labels are reversed on the left side of the overview chart?

<img width="483" alt="Screen Shot 2019-12-19 at 10 07 45 AM" src="https://user-images.githubusercontent.com/10912958/71198305-58248700-2248-11ea-9dbe-99fbd4bd86a1.png">

**Comment by SachaG** [comment]
No the year labels seem correct here?
