### ISSUE TITLE
Languages → .NET 

### ISSUE THREAD

**Issue by Daniel15** [StateOfJS/State-of-JS-2019#32]
![image](https://user-images.githubusercontent.com/91933/71201304-96bd4000-224e-11ea-912c-2276cf26f36c.png)

.NET is a platform, not a language. There are several languages built on top of .NET, such as C#, F#, VB.NET, etc. Because of that, it doesn't really make sense to list it as a language here - It'd be like listing both "Java" and "JVM" as separate languages 😄 

It seems like it'd make the most sense to combine these two together into "C#", if people didn't enter other .NET languages (like F#) as freeform text

**Comment by SachaG** [comment]
Thanks, that makes sense.

**Comment by petrkoula** [comment]
It't has not been fixed yet..

**Comment by SachaG** [comment]
We'll fix it for next year. We can't change the existing data.
