### ISSUE TITLE
Vertical bar labels missing digits on narrow window sizes/mobile browsers

### ISSUE THREAD

**Issue by daprice** [StateOfJS/State-of-JS-2019#33]
See screenshot from iPhone X, iOS 13.3 Safari. The “intermediate”, “advanced”, and “expert” bars appear to be showing 3.7, 6.4, and 9.9 when they are really 33.7%, 16.4%, and 39.9%.

![08B119EC-3865-4B97-AEEB-254CB91F48E9](https://user-images.githubusercontent.com/3615519/71201889-99c12c00-2260-11ea-93d1-bb86a66c2eb1.png)

**Comment by plouc** [comment]
Fixed by https://github.com/StateOfJS/State-of-JS-2019/commit/5e312e665dde1d2ff7eeafd44f22380d4bfccd84
