### ISSUE TITLE
11 freeform answers for typescript were left out

### ISSUE THREAD

**Issue by Mouvedia** [StateOfJS/State-of-JS-2019#34]
- check https://2019.stateofjs.com/javascript-flavors/other-tools/
- realize that typescript is listed as other
- typescript already got [its own category](https://2019.stateofjs.com/javascript-flavors/typescript/)

You should count them as well.

BTW https://2019.stateofjs.com/other-tools/#text_editors_others has the same problem.

**Comment by SachaG** [comment]
Yes we currently don't have a process to add freeform answers to "regular" answers when they overlap. It's a bit of an edge case but we want to rethink how freeform answers are collected eventually anyway.
