### ISSUE TITLE
Typo in the word "Clojurescript" in the Javascript Flavors survey 

### ISSUE THREAD

**Issue by PaulKleinschmidt** [StateOfJS/State-of-JS-2019#36]
See screenshot below. Closurecript is spelled "ojurescript" on the left of the graph and "closurescri" on the right of the graph.

<img width="1440" alt="Screen Shot 2019-12-19 at 1 28 21 PM" src="https://user-images.githubusercontent.com/32469657/71211364-d0e50c80-2263-11ea-937f-4258f7b93f17.png">

**Comment by SachaG** [comment]
That's because the labels get cut off. I'll give them more breathing room, thanks.
