### ISSUE TITLE
State of JS t-shirt sizes

### ISSUE THREAD

**Issue by umpc** [StateOfJS/State-of-JS-2019#40]
Any plans to add a men's XS size? I saw a men's XS size available on the page selling the blank t-shirt but not for the actual State of JS t-shirt.

Thanks.

**Comment by SachaG** [comment]
Sorry I was in a bit of a hurry and didn't add all available sizes when I set things up. I'll try to find some time soon to add XS, XXL, and XXXXL.

**Comment by umpc** [comment]
I just ordered and looks like it processed. Thank you!
