### ISSUE TITLE
Storybook is no testing framework

### ISSUE THREAD

**Issue by timbergus** [StateOfJS/State-of-JS-2019#42]
Storybook is a tool to create component libraries, but not a testing framework. You can add a testing framework like Jest to test the components you have created, but Storybook, as React Styleguidist are only tools to create and visualize components outside your main application.

**Comment by SachaG** [comment]
This is not a very useful argument to have unless you have a better place to put it? At the end of the day we do need to include things somewhere, and having even more categories just makes comparisons and navigation harder. So I think putting Storybook with testing frameworks is good enough.

**Comment by timbergus** [comment]
OK, sorry.
