### ISSUE TITLE
Block translations not appearing

### ISSUE THREAD

**Issue by marceloemanoel** [StateOfJS/State-of-JS-2019#45]
Hey y'all,

First of all thanks for your awesome work! I'm translating the survey results to Brazilian Portuguese but the block translation isn't being presented on the page. I did a little investigation and found out that on the `block_templates.yaml` file the `pageIntroductionTemplate` is hardcoding the 'en-US' locale. Changing it to 'pt-BR' does show the translation but then I loose the original text. 

```
pageIntroductionTemplate:
    blockType: PageIntroductionBlock
    dataPath: '${pageId}_introduction.html'
    query: >
        ${pageId}_introduction: markdownRemark(
            frontmatter: {
                type:   { eq: "introduction" }
                page:   { eq: "${pageId}" }
                locale: { eq: "en-US" }
            }
        ) {
            html
        }
```

**Comment by SachaG** [comment]
Oh good point. I guess we didn't consider how to handle translations within our sitemap templating system… It looks like it might be a little tricky to fix so I'll take a look later this week.

**Comment by SachaG** [comment]
OK it should work better now.
