### ISSUE TITLE
Some Rankings graph/chart are counter-intuitive

### ISSUE THREAD

**Issue by sebranly** [StateOfJS/State-of-JS-2019#53]
https://2019.stateofjs.com/back-end/

If you take a look at `express`' interest, it looks like it's going down because of `gatsby` and `nextjs` having superior %, but in reality, `express`' interest increased over time.

<img width="1304" alt="Screenshot 2019-12-25 at 19 48 11" src="https://user-images.githubusercontent.com/25478895/71449596-35b2d200-2750-11ea-82e3-53f1ab32a301.png">

**Comment by sebranly** [comment]
On https://2019.stateofjs.com/mobile-desktop/, such a counter-intuitive point can be make as well for both `electron` and `reactnative`

**Comment by SachaG** [comment]
I guess that could be solved by having Express start lower. But I don't know if there's an easy algorithm to determine that without having to do a lot of manual work… I guess maybe the chart could try to "propagate" the last or first known value for each item throughout all the verticals to avoid this kind of inconsistency? cc @plouc

**Comment by sebranly** [comment]
(A bit surprised to see this closed without a proper explanation tbh)

**Comment by SachaG** [comment]
Not sure what else to say, that's just how the chart works… If you run a race three years in a row and run it in 12 min, 11 min, and 10 min you can still finish first, second, and then third even though your performance is improving if other competitors run even faster than you.
