### ISSUE TITLE
Salary, years of XP, company size and many usage charts are not displaying data

### ISSUE THREAD

**Issue by hu0p** [StateOfJS/State-of-JS-2019#62]
The data is at least being populated in some capacity because it's visible in the export modals. See the screenshots below for visual examples.

Screenshots:
![Screen Shot 2019-12-30 at 2 07 53 PM](https://user-images.githubusercontent.com/17230438/71596670-2ea01100-2b0e-11ea-9ec0-694ea31c80ab.png)

![Screen Shot 2019-12-30 at 2 08 17 PM](https://user-images.githubusercontent.com/17230438/71596662-2ba52080-2b0e-11ea-99d3-c14e1d135855.png)

EDIT: Just to confirm, none of the usage charts are displaying data. Additionally, there are no production console errors.

**Comment by hu0p** [comment]
I attempted to diagnose this a bit, but I unfortunately can't get very far because I don't have the `API_URL` env variable. 

However, if I had to hazard a guess, I'd say it's because you've removed `range_` prefix from the values in your API for these arrays:

```javascript
export const salaryArray = [
    'range_work_for_free',
    'range_0_10',
    'range_10_30',
    'range_30_50',
    'range_50_100',
    'range_100_200',
    'range_more_than_200'
]

export const companySizeArray = [
    'range_1',
    'range_1_5',
    'range_5_10',
    'range_10_20',
    'range_20_50',
    'range_50_100',
    'range_100_1000',
    'range_more_than_1000'
]

export const workExperienceArray = [
    'range_less_than_1',
    'range_1_2',
    'range_2_5',
    'range_5_10',
    'range_10_20',
    'range_more_than_20'
]
```

Good luck!

**Comment by SachaG** [comment]
Yeah we've been tweaking some things in the API. It should be fixed soon, thanks for letting us know!
